server:
  port: 8180
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


app:
  job:
    save_path: /Users/jicg/Desktop/tools/job.json
  url: /
  ip-filter:
    enable: true
    exclude-path-patterns:
      - /api/wm/*/notice
    cidr: 192.168.0.0/16
  auth:
    enable: true
    type: simple

